### ISSUE TITLE
compile error npm start

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-pwa-toolkit#25]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1 C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit
`-- @stencil/core@0.6.1
```

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
```
C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit>npm start

> @stencil/starter@0.0.1 start C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit
> npm run dev


> @stencil/starter@0.0.1 dev C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[17:01.0]  @stencil/core v0.6.1
[17:01.0]  build, app, dev mode, started ...
[17:01.0]  compile started ...
[17:04.1]  compile finished in 3.06 s
{ Error: Could not resolve './dist/collection/components/lazy-img/lazy-img.js' from entry:lazy-img
    at error (C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit\node_modules\@stencil\core\node_modules\rollup\dist\rollup.js:170:15)
    at C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit\node_modules\@stencil\core\node_modules\rollup\dist\rollup.js:19580:25
    at <anonymous> code: 'UNRESOLVED_IMPORT' }

[ ERROR ]  Could not resolve './dist/collection/components/lazy-img/lazy-img.js' from entry:lazy-img

[ ERROR ]  rollup died at
           C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit\node_modules\@stencil\core\dist\compiler\index.js:2061:19
           at Generator.throw (<anonymous>) at rejected
           (C:\Users\daniel.ehrhardt\Desktop\Alles\Geschäftlich\ionic-pwa-toolkit\node_modules\@stencil\core\dist\compiler\index.js:2017:65)
           at <anonymous>

[17:04.9]  build failed, watching for changes... in 3.87 s

```
**Expected behavior:**
App should start dev build

**Steps to reproduce:**
Clone the repo run npm install and then npm start

**Related code:**

```
node -v
v8.9.4
npm -v (same with 5.6.0)
5.7.1
Windows 10 64 bit
```

**Comment by danielehrhardt** [comment]
It's the ä in my Path 
C:\Users\daniel.ehrhardt\Desktop\Alles\**Geschäftlich**\ionic-pwa-toolkit>

**Comment by jgw96** [comment]
Hey @danielehrhardt , this is an interesting issue, thanks for debugging! Since this seems like a rollup issue and not a Stencil issue, I would open an issue on their repo https://github.com/rollup/rollup . Thanks for using Stencil!
