### ISSUE TITLE
Updating @stencil/core causes test to fail on Windows

### ISSUE THREAD

**Issue by tja4472** [ionic-team/ionic-pwa-toolkit#44]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
0.7.16+
```

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

```bash
PS C:\VSCode\git-hub-tim\pwa-toolbox-firebase> npm test

> @stencil/starter@0.0.1 test C:\VSCode\git-hub-tim\pwa-toolbox-firebase
> jest --no-cache

 FAIL  src\components\app-home\app-home.spec.ts
  ● Test suite failed to run

    Cannot find module 'C:VSCodegit-hub-timpwa-toolbox-firebase
    ode_modules@stencilcoredist estingindex.js' from 'app-home.tsx'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (src/components/app-home/app-home.tsx:3:22)

 FAIL  src\components\app-profile\app-profile.spec.ts
  ● Test suite failed to run

    Cannot find module 'C:VSCodegit-hub-timpwa-toolbox-firebase
    ode_modules@stencilcoredist estingindex.js' from 'app-profile.tsx'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (src/components/app-profile/app-profile.tsx:3:22)

 FAIL  src\components\my-app\my-app.spec.ts
  ● Test suite failed to run

    Cannot find module 'C:VSCodegit-hub-timpwa-toolbox-firebase
    ode_modules@stencilcoredist estingindex.js' from 'my-app.tsx'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (src/components/my-app/my-app.tsx:3:22)
```
**Expected behavior:**

**Steps to reproduce:**

Update package.json
npm install
npm test
**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are tracking this issue here https://github.com/ionic-team/stencil/issues/700 and will have a fix available soon.
