### ISSUE TITLE
events.js:183       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-pwa-toolkit#53]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
peter@Merry-Christmas MINGW64 /c/ae/adaept.com/aepwa (master)
$ npm list @stencil/core
@stencil/starter@0.0.1 C:\ae\adaept.com\aepwa
`-- @stencil/core@0.7.24
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Fail

**Expected behavior:**
Run

**Steps to reproduce:**
```
peter@Merry-Christmas MINGW64 /c/ae/adaept.com
$ git clone https://github.com/ionic-team/ionic-pwa-toolkit.git aepwa
Cloning into 'aepwa'...
remote: Counting objects: 371, done.
remote: Compressing objects: 100% (56/56), done.
Receiving oremote: Total 371 (delta 55), reused 83 (delta 44), pack-reused 267
Receiving objects: 100% (371/371), 284.98 KiB | 1.27 MiB/s, done.
Resolving deltas: 100% (217/217), done.

peter@Merry-Christmas MINGW64 /c/ae/adaept.com
$ cd aepwa

peter@Merry-Christmas MINGW64 /c/ae/adaept.com/aepwa (master)
$ git remote rm origin

peter@Merry-Christmas MINGW64 /c/ae/adaept.com/aepwa (master)
$ npm i

> node-sass@4.7.2 install C:\ae\adaept.com\aepwa\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\peter\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> node-sass@4.7.2 postinstall C:\ae\adaept.com\aepwa\node_modules\node-sass
> node scripts/build.js

Binary found at C:\ae\adaept.com\aepwa\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 858 packages from 485 contributors in 26.945s

peter@Merry-Christmas MINGW64 /c/ae/adaept.com/aepwa (master)
$ npm start

> @stencil/starter@0.0.1 start C:\ae\adaept.com\aepwa
> npm run dev


> @stencil/starter@0.0.1 dev C:\ae\adaept.com\aepwa
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3333
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (C:\ae\adaept.com\aepwa\node_modules\@stencil\dev-server\dist\index.js:88:64)
    at Generator.next (<anonymous>)
    at fulfilled (C:\ae\adaept.com\aepwa\node_modules\@stencil\dev-server\dist\index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[03:04.6]  @stencil/core v0.7.24
[03:04.6]  build, app, dev mode, started ...
[03:04.6]  compile started ...
[03:08.7]  compile finished in 4.09 s
[03:08.7]  module map started ...
[03:09.5]  module map finished in 785 ms
[03:10.6]  generate bundles started ...
[03:10.6]  generate bundles finished in 9 ms
[03:10.6]  generate app files started ...
[03:10.6]  compile global style start ...
[03:10.6]  compile global style finish in less than 1 ms
[03:10.6]  generate app files finished in 34 ms
[03:12.2]  build finished, watching for changes... in 7.62 s
```

**Other information:**
The app says build finished but does not open.

**Comment by peterennis** [comment]
Ignore the error, build for prod, and deploy to firebase.

```
C:\ae\adaept.com\aepwa>firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\ae\adaept.com\aepwa

Before we get started, keep in mind:

  * You are currently outside your home directory

? Are you ready to proceed? Yes
? Which Firebase CLI features do you want to setup for this folder? Press Space to select features, then Enter to confi
rm your choices. Hosting: Configure and deploy Firebase Hosting sites

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Select a default Firebase project for this directory: aepwa-dev (aepwa-dev)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory? www
? Configure as a single-page app (rewrite all urls to /index.html)? No
+  Wrote www/404.html
? File www/index.html already exists. Overwrite? No
i  Skipping write of www/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!

C:\ae\adaept.com\aepwa>firebase deploy

=== Deploying to 'aepwa-dev'...

i  deploying hosting
i  hosting: preparing www directory for upload...
+  hosting: 785 files uploaded successfully

+  Deploy complete!

Project Console: https://console.firebase.google.com/project/aepwa-dev/overview
Hosting URL: https://aepwa-dev.firebaseapp.com

C:\ae\adaept.com\aepwa>
```

**Comment by peterennis** [comment]
Run Lighthouse audit.
Is the pwa toolkit intended to be a best practices guide so that the non
supported areas will be fixed for the sample?
Docs update to point to solutions?

![capture274](https://user-images.githubusercontent.com/140737/38784197-5626ce26-40c3-11e8-8776-e0c821ba75a5.png)

**Comment by jgw96** [comment]
Hey @peterennis ! The first error looks as though you have another process running on 3333, perhaps another instance of Stencil? On the second issue, our service workers are currently running into this chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=833501, which is why lighthouse is knocking off your PWA score. Also, are you following these directions? https://github.com/ionic-team/ionic-pwa-toolkit#hosting

**Comment by peterennis** [comment]
Followed the steps. Did not do H2 push. Using Firebase hosting. Saw this:

```
** Note: In an upcoming release we will be automatically generating this H2 push config for you meaning you will not have to do any of the above anymore **
```

@jgw96,  What RC is this planned for?

**Comment by peterennis** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=832202

Comment 6 by jsb...@chromium.org, Today (9 hours ago)
Issue 833501 has been merged into this issue.

**Comment by jgw96** [comment]
@peterennis that feature is actually a little delayed at the moment and I do not have a timeframe for it now. I am going to close this issue for now as its not really an issue, but feel free to contact me on the stencil slack https://stencil-worldwide.herokuapp.com/ .
